# Identificação do projeto
sonar.projectKey=pedrovieira249_ci-js-sonarcloud
sonar.organization=pedrovieira249
sonar.projectVersion=1.0

# Encoding
sonar.sourceEncoding=UTF-8

# Diretórios
sonar.sources=src
sonar.tests=src

# Arquivos de teste
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# Exclusões IMPORTANTES (evita travamentos e análise desnecessária)
sonar.exclusions=node_modules/**,coverage/**,dist/**,build/**,.scannerwork/**,**/*.test.js

# Cobertura de código
sonar.javascript.lcov.reportPaths=coverage/lcov.info